// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sozctsrxqeqvubgufiuq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNvemN0c3J4cWVxdnViZ3VmaXVxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzQ5MzM1NTYsImV4cCI6MjA5MDUwOTU1Nn0.nT213DdxUxO7b1zA-6W1uElUTqyt-eSAQr74bWDzxW4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
